<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.163" timestamp="2025-06-05T16:31:39.141261-05:00" hostname="Ing-Sebastian"><testcase classname="" name="tests.test_hello" time="0.000"><error message="collection failure">C:\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&lt;frozen importlib._bootstrap&gt;:1387: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1360: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1310: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:488: in _call_with_frames_removed
    ???
&lt;frozen importlib._bootstrap&gt;:1387: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1360: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1331: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:935: in _load_unlocked
    ???
&lt;frozen importlib._bootstrap_external&gt;:1026: in exec_module
    ???
&lt;frozen importlib._bootstrap&gt;:488: in _call_with_frames_removed
    ???
tests\__init__.py:1: in &lt;module&gt;
    test = pytest.mark.test
           ^^^^^^
E   NameError: name 'pytest' is not defined</error></testcase></testsuite></testsuites>